version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: nest_mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  nestjs:
    build: .
    container_name: nestjs
    environment:
      MONGODB_URI: mongodb://root:password@mongodb:27017/nest_mongo
    depends_on:
      - mongodb
    ports:
      - 3000:3000

volumes:
  mongo-data:
